apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc
  namespace: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: io.ember-csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
## We can provide parameters to the driver if it supports them
# parameters:
## For example for drivers supporting pools, when we have multiple pools
#  pool_name: rhos_cinder
## QoS parameters must have the qos_ prefix
#  qos_maxIOPS: "1000"
## Extra specs must have the xtra_ prefix
#  xtra_hpe3par:compression: "true"
